baseurl = "https://www.ulampinoy.com/"
title = "The Ulampinoy Project"
theme = "adobo"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
	archive = "archives"
	post = "posts"
	video = "videos"
	about = "about"
	ebook = "ebook"

[params.hero]
	title = "Lutong bahay na pun√¥ ng pagmamahal, kulay at sarap"

# Pagination
paginate = 10
paginatePath = "page"
